### ISSUE TITLE
undefined method `apply_resource_includes'

### ISSUE THREAD

**Issue by sedubois** [XPBytes/administrate-base_controller#8]
Hello and thanks for this gem which I am trying to use to solve the JSON serialization issue [described in administrate-field-jsonb](https://github.com/codica2/administrate-field-jsonb/issues/1) (I am trying to use administrate-base_controller as recommended in the README of administrate-serialized_fields).

However, after including this base controller I get this error for the index action: 
`undefined method 'apply_resource_includes' for #<Admin::AdministratorsController:0x00007fa25d3696e0> Did you mean? apply_collection_includes`

I can workaround the issue by avoiding this gem and instead copying the code required for the serialization, but still wanted to raise this observation here.

I am using Rails 5.2.3, Administrate 0.12.0.

**Comment by SleeplessByte** [comment]
Sweet. They changed this from 0.11.0 to 0.12.0. I'll fix.
